version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: studyjpa-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ?{MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ?{MYSQL_DATABASE}
      MYSQL_USER: ?{MYSQL_USER}
      MYSQL_PASSWORD: ?{MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - studyjpa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studyjpa-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ?{SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ?{MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ?{MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
    ports:
      - "8080:8080"
    networks:
      - studyjpa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: studyjpa-nginx
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - studyjpa-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local

networks:
  studyjpa-network:
    driver: bridge